services:
  - type: web
    name: tradingview-alert-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: ls -la
    workingDirectory: src
    envVars:
      - key: BOT_TOKEN
        value: "your-telegram-bot-token"
      - key: CHAT_ID
        value: "your-chat-id"
